# # 使用官方 Node.js 镜像作为基础镜像
# FROM node:16 AS builder

# # 设置工作目录
# WORKDIR /app

# # 复制 package.json 和 package-lock.json
# COPY package.json ./

# # 安装依赖
# RUN npm install

# # 将项目文件复制到容器中
# COPY . .

# # 构建 Vue 应用
# RUN npm run build

# # 使用 nginx 镜像作为基础镜像，来提供前端应用的静态文件
# FROM nginx:alpine

# # 将构建后的前端应用文件从 builder 阶段复制到 nginx 的 web 根目录
# COPY --from=builder /app/dist /usr/share/nginx/html
# COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# # 暴露 nginx 端口
# EXPOSE 80

# # 启动 nginx
# CMD ["nginx", "-g", "daemon off;"]


# 第一阶段：node镜像打包
FROM node:latest AS frontend-builder
WORKDIR /build-app
COPY . .
RUN npm config set registry https://registry.npmmirror.com
RUN npm install
RUN npm run build

# 第二阶段：nginx打包
FROM nginx:latest
EXPOSE 80
WORKDIR /app
# 替换nginx配置
COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf
# 将第一阶段的静态文件复制到nginx中
RUN rm -rf /usr/share/nginx/html
RUN mkdir /usr/share/nginx/html
COPY --from=frontend-builder /build-app/dist /usr/share/nginx/html

# 运行
CMD ["nginx", "-g", "daemon off;"]

